#!/usr/bin/env bash
# Upload the manifest + brotli blob generated by
# D:/LyricLens/scripts/preprocess-jlpt.mjs into the LYRICLENS_DICTS KV
# namespace under the "jlpt/" family prefix.
#
# Ordering matters: blob is uploaded first, THEN the manifest that
# points at it. KV is eventually consistent (~60s at edge); if the
# manifest lands first, clients following it will 404 on the blob
# until propagation completes.
#
# Usage:
#   KV_NAMESPACE_ID=<hex> \
#   OUT_DIR=D:/LyricLens/scripts/out/jlpt \
#   bash upload-blob.sh
set -eu
set -o pipefail 2>/dev/null || true

ACCOUNT_ID="${CLOUDFLARE_ACCOUNT_ID:-5e96dfd2bf22d385e4ffdaa794d74676}"
OUT_DIR="${OUT_DIR:-/mnt/d/LyricLens/scripts/out/jlpt}"
FAMILY="${FAMILY:-jlpt}"

if [[ -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  if [[ -f "$HOME/.config/codex/private.env" ]]; then
    # shellcheck disable=SC1091
    source "$HOME/.config/codex/private.env"
  fi
fi
if [[ -z "${CLOUDFLARE_API_TOKEN:-}" ]]; then
  echo "missing CLOUDFLARE_API_TOKEN — export it or put it in ~/.config/codex/private.env" >&2
  exit 1
fi
if [[ -z "${KV_NAMESPACE_ID:-}" ]]; then
  echo "missing KV_NAMESPACE_ID — export the LYRICLENS_DICTS namespace id" >&2
  exit 1
fi
if [[ ! -d "$OUT_DIR" ]]; then
  echo "OUT_DIR not found: $OUT_DIR" >&2
  exit 1
fi

MANIFEST="$OUT_DIR/manifest.json"
if [[ ! -f "$MANIFEST" ]]; then
  echo "manifest.json missing at $MANIFEST — run preprocess-jlpt.mjs first" >&2
  exit 1
fi

# Extract the "latest" key from the manifest so we can find the matching
# blob without hard-coding a filename.
LATEST=$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d["latest"])' "$MANIFEST")
BLOB_FILE=$(python3 -c 'import json,sys,os; d=json.load(open(sys.argv[1])); u=d["sources"][d["latest"]]["url"]; print(os.path.basename(u))' "$MANIFEST")
BLOB_PATH="$OUT_DIR/$BLOB_FILE"
if [[ ! -f "$BLOB_PATH" ]]; then
  echo "blob missing: $BLOB_PATH" >&2
  exit 1
fi

# Cross-check the manifest's declared sha256 against the on-disk blob
# before we upload anything. A drift here means the manifest was
# generated against a different blob than we're about to publish, which
# would break the desktop client's integrity check.
DECLARED=$(python3 -c 'import json,sys; d=json.load(open(sys.argv[1])); print(d["sources"][d["latest"]]["sha256"])' "$MANIFEST")
ACTUAL=$(sha256sum "$BLOB_PATH" | awk '{print $1}')
if [[ "$DECLARED" != "$ACTUAL" ]]; then
  echo "sha256 mismatch: manifest says $DECLARED, disk blob is $ACTUAL — regenerate before uploading" >&2
  exit 1
fi

BLOB_KEY="$FAMILY/$BLOB_FILE"
MANIFEST_KEY="$FAMILY/manifest.json"

echo "== step 1: upload blob =="
echo "  key = $BLOB_KEY"
echo "  size = $(wc -c < "$BLOB_PATH") bytes"
echo "  sha256 = $ACTUAL"
curl --silent --show-error --fail \
  -X PUT \
  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  -H "Content-Type: application/octet-stream" \
  --data-binary "@$BLOB_PATH" \
  "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/storage/kv/namespaces/$KV_NAMESPACE_ID/values/$BLOB_KEY" \
  | python3 -c 'import json,sys; d=json.load(sys.stdin); print("blob upload ok" if d.get("success") else json.dumps(d))'

echo
echo "waiting 60s for KV edge propagation before publishing manifest…"
sleep 60

echo "== step 2: upload manifest =="
echo "  key = $MANIFEST_KEY"
echo "  latest = $LATEST"
curl --silent --show-error --fail \
  -X PUT \
  -H "Authorization: Bearer $CLOUDFLARE_API_TOKEN" \
  -H "Content-Type: application/json" \
  --data-binary "@$MANIFEST" \
  "https://api.cloudflare.com/client/v4/accounts/$ACCOUNT_ID/storage/kv/namespaces/$KV_NAMESPACE_ID/values/$MANIFEST_KEY" \
  | python3 -c 'import json,sys; d=json.load(sys.stdin); print("manifest upload ok" if d.get("success") else json.dumps(d))'

echo
echo "done. verify with:"
echo "  curl -sfI https://dicts.yoru-and-akari.dev/$MANIFEST_KEY"
echo "  curl -sfI https://dicts.yoru-and-akari.dev/$BLOB_KEY"
